image: docker:20.10.14

ci:
  services:
    - docker:20.10.14-dind
  variables:
    TURBO_DOCKER_IMAGE_PREFIX: $CI_REGISTRY/$CI_PROJECT_PATH
  script:
    - apk update && apk add --no-cache git make protobuf-dev nodejs yarn
    - yarn install
    - yarn turbo run build:turbo

    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - yarn turbo run build:docker
